==537401== Memcheck, a memory error detector
==537401== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==537401== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==537401== Command: python run.py
==537401== Parent PID: 526800
==537401== 
==537401== Conditional jump or move depends on uninitialised value(s)
==537401==    at 0x6BFEC33: __intel_sse2_strrchr (in /home/guen/anaconda3/lib/libiomp5.so)
==537401==    by 0x6BAB1B5: _INTERNAL744921f0::__kmp::init_dl_data() (in /home/guen/anaconda3/lib/libiomp5.so)
==537401==    by 0x6BAB116: __sti__$E (in /home/guen/anaconda3/lib/libiomp5.so)
==537401==    by 0x6C13155: ??? (in /home/guen/anaconda3/lib/libiomp5.so)
==537401==    by 0x6AE4452: ??? (in /home/guen/anaconda3/lib/libiomp5.so)
==537401==    by 0x1: ???
==537401==    by 0x4011B4B: call_init.part.0 (dl-init.c:58)
==537401==    by 0x4011C90: call_init (dl-init.c:30)
==537401==    by 0x4011C90: _dl_init (dl-init.c:119)
==537401==    by 0x4DEC914: _dl_catch_exception (dl-error-skeleton.c:182)
==537401==    by 0x401642C: dl_open_worker (dl-open.c:758)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401== 
==537401== Invalid read of size 8
==537401==    at 0x4020A78: strncmp (strcmp.S:175)
==537401==    by 0x40066ED: is_dst (dl-load.c:209)
==537401==    by 0x4009A2E: _dl_dst_count (dl-load.c:246)
==537401==    by 0x4009A2E: expand_dynamic_string_token (dl-load.c:388)
==537401==    by 0x4009BE1: fillin_rpath (dl-load.c:460)
==537401==    by 0x4009F43: decompose_rpath.isra.0 (dl-load.c:631)
==537401==    by 0x400A915: cache_rpath (dl-load.c:673)
==537401==    by 0x400A915: cache_rpath (dl-load.c:654)
==537401==    by 0x400A915: _dl_map_object (dl-load.c:2041)
==537401==    by 0x400F504: openaux (dl-deps.c:64)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x400F952: _dl_map_object_deps (dl-deps.c:248)
==537401==    by 0x4015D9F: dl_open_worker (dl-open.c:571)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401==  Address 0x4fe6849 is 9 bytes inside a block of size 14 alloc'd
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x401F5CE: strdup (strdup.c:42)
==537401==    by 0x4009ED4: decompose_rpath.isra.0 (dl-load.c:606)
==537401==    by 0x400A915: cache_rpath (dl-load.c:673)
==537401==    by 0x400A915: cache_rpath (dl-load.c:654)
==537401==    by 0x400A915: _dl_map_object (dl-load.c:2041)
==537401==    by 0x400F504: openaux (dl-deps.c:64)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x400F952: _dl_map_object_deps (dl-deps.c:248)
==537401==    by 0x4015D9F: dl_open_worker (dl-open.c:571)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401==    by 0x4E7C34B: dlopen_doit (dlopen.c:66)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401== 
==537401== Invalid read of size 8
==537401==    at 0x4020A78: strncmp (strcmp.S:175)
==537401==    by 0x40066ED: is_dst (dl-load.c:209)
==537401==    by 0x40098AE: _dl_dst_substitute (dl-load.c:288)
==537401==    by 0x4009BE1: fillin_rpath (dl-load.c:460)
==537401==    by 0x4009F43: decompose_rpath.isra.0 (dl-load.c:631)
==537401==    by 0x400A915: cache_rpath (dl-load.c:673)
==537401==    by 0x400A915: cache_rpath (dl-load.c:654)
==537401==    by 0x400A915: _dl_map_object (dl-load.c:2041)
==537401==    by 0x400F504: openaux (dl-deps.c:64)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x400F952: _dl_map_object_deps (dl-deps.c:248)
==537401==    by 0x4015D9F: dl_open_worker (dl-open.c:571)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401==  Address 0x4fe6849 is 9 bytes inside a block of size 14 alloc'd
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x401F5CE: strdup (strdup.c:42)
==537401==    by 0x4009ED4: decompose_rpath.isra.0 (dl-load.c:606)
==537401==    by 0x400A915: cache_rpath (dl-load.c:673)
==537401==    by 0x400A915: cache_rpath (dl-load.c:654)
==537401==    by 0x400A915: _dl_map_object (dl-load.c:2041)
==537401==    by 0x400F504: openaux (dl-deps.c:64)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x400F952: _dl_map_object_deps (dl-deps.c:248)
==537401==    by 0x4015D9F: dl_open_worker (dl-open.c:571)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401==    by 0x4E7C34B: dlopen_doit (dlopen.c:66)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401== 
==537468== 
==537468== HEAP SUMMARY:
==537468==     in use at exit: 4,968,047 bytes in 3,871 blocks
==537468==   total heap usage: 38,107,197 allocs, 38,103,326 frees, 1,787,797,628 bytes allocated
==537468== 
==537468== 32 bytes in 1 blocks are definitely lost in loss record 330 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x216177: PyThread_allocate_lock (thread_pthread.h:289)
==537468==    by 0x2DFF92: _PyRuntimeState_Init_impl (pystate.c:53)
==537468==    by 0x2DFF92: _PyRuntimeState_Init (pystate.c:70)
==537468==    by 0x2E0027: _PyRuntime_Initialize (pylifecycle.c:96)
==537468==    by 0x32D10D: pymain_cmdline_impl (main.c:2885)
==537468==    by 0x32D10D: pymain_cmdline (main.c:2955)
==537468==    by 0x32D10D: pymain_init (main.c:2996)
==537468==    by 0x32FC9B: pymain_main (main.c:3409)
==537468==    by 0x3300BB: _Py_UnixMain (main.c:3449)
==537468==    by 0x4CB00B2: (below main) (libc-start.c:308)
==537468== 
==537468== 32 bytes in 1 blocks are definitely lost in loss record 332 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x216145: PyThread_allocate_lock (thread_pthread.h:289)
==537468==    by 0x2289A0: _PyImport_AcquireLock (import.c:161)
==537468==    by 0x228A09: _imp_acquire_lock_impl (import.c:256)
==537468==    by 0x228A09: _imp_acquire_lock (import.c.h:43)
==537468==    by 0x268FF0: _PyMethodDef_RawFastCallKeywords (call.c:633)
==537468==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537468==    by 0x2CDA5C: call_function (ceval.c:4568)
==537468==    by 0x2CDA5C: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x223C0E: _PyObject_FastCallDict (call.c:125)
==537468== 
==537468== 40 bytes in 1 blocks are definitely lost in loss record 335 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x400F71E: _dl_map_object_deps (dl-deps.c:438)
==537468==    by 0x4015D9F: dl_open_worker (dl-open.c:571)
==537468==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537468==    by 0x40155F9: _dl_open (dl-open.c:837)
==537468==    by 0x4E7C34B: dlopen_doit (dlopen.c:66)
==537468==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537468==    by 0x4DEC982: _dl_catch_error (dl-error-skeleton.c:227)
==537468==    by 0x4E7CB58: _dlerror_run (dlerror.c:170)
==537468==    by 0x4E7C3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==537468==    by 0x63D7317: PyInit__mklinit (in /home/guen/anaconda3/lib/python3.7/site-packages/mkl/_mklinit.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x327694: _PyImport_LoadDynamicModuleWithSpec (importdl.c:159)
==537468== 
==537468== 47 bytes in 1 blocks are definitely lost in loss record 336 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x4018CED: _dl_exception_create (dl-exception.c:78)
==537468==    by 0x4DEC807: _dl_signal_error (dl-error-skeleton.c:117)
==537468==    by 0x400AD89: _dl_map_object (dl-load.c:2231)
==537468==    by 0x4015D36: dl_open_worker (dl-open.c:513)
==537468==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537468==    by 0x40155F9: _dl_open (dl-open.c:837)
==537468==    by 0x4E7C34B: dlopen_doit (dlopen.c:66)
==537468==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537468==    by 0x4DEC982: _dl_catch_error (dl-error-skeleton.c:227)
==537468==    by 0x4E7CB58: _dlerror_run (dlerror.c:170)
==537468==    by 0x4E7C3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==537468== 
==537468== 65 (32 direct, 33 indirect) bytes in 1 blocks are definitely lost in loss record 352 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x6F81A41: _buffer_get_info (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x6F81EFA: array_getbuffer (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x8A573BF: __Pyx__GetBufferAndValidate.constprop.63 (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x8A5CAF2: __pyx_f_5numpy_6random_14_bit_generator_12SeedSequence_mix_entropy (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x8A62BEF: __pyx_pw_5numpy_6random_14_bit_generator_12SeedSequence_1__init__ (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x27DBC6: type_call (typeobject.c:971)
==537468==    by 0x8A586AE: __Pyx__PyObject_CallOneArg (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x8A62577: __pyx_pw_5numpy_6random_14_bit_generator_12BitGenerator_1__init__ (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x2DA1CB: wrap_init (typeobject.c:5880)
==537468==    by 0x23AF37: wrapperdescr_raw_call.isra.1 (descrobject.c:346)
==537468==    by 0x23AF37: wrapperdescr_call (descrobject.c:392)
==537468==    by 0x924C446: __pyx_pw_5numpy_6random_8_mt19937_7MT19937_1__init__ (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_mt19937.cpython-37m-x86_64-linux-gnu.so)
==537468== 
==537468== 208 (80 direct, 128 indirect) bytes in 1 blocks are definitely lost in loss record 394 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x145B7173: __pyx_f_10structures_newnode (structures.c:2365)
==537468==    by 0x6156BBE: __pyx_f_7amazons_7Amazons_game (amazons.c:4361)
==537468==    by 0x615242D: __pyx_pf_7amazons_2main (amazons.c:5476)
==537468==    by 0x615242D: __pyx_pw_7amazons_3main (amazons.c:5364)
==537468==    by 0x231B9D: PyObject_Call (call.c:245)
==537468==    by 0x2CA9F4: do_call_core (ceval.c:4645)
==537468==    by 0x2CA9F4: _PyEval_EvalFrameDefault (ceval.c:3191)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468== 
==537468== 320 bytes in 1 blocks are possibly lost in loss record 405 of 1,036
==537468==    at 0x4A3DB6D: calloc (vg_replace_malloc.c:1117)
==537468==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==537468==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==537468==    by 0x4C70322: allocate_stack (allocatestack.c:622)
==537468==    by 0x4C70322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==537468==    by 0x2DF130: PyThread_start_new_thread (thread_pthread.h:222)
==537468==    by 0x2F2962: thread_PyThread_start_new_thread (_threadmodule.c:1067)
==537468==    by 0x26908F: _PyMethodDef_RawFastCallKeywords (call.c:698)
==537468==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537468==    by 0x2CD323: call_function (ceval.c:4568)
==537468==    by 0x2CD323: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 414 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x17E48A: _PyObject_CallFunctionVa (call.c:961)
==537468==    by 0x2883B6: callmethod (call.c:1031)
==537468==    by 0x2883B6: PyObject_CallMethod (call.c:1050)
==537468==    by 0x327DE0: initimport (pylifecycle.c:327)
==537468==    by 0x32C875: _Py_InitializeCore_impl (pylifecycle.c:818)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 415 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x2CA9F4: do_call_core (ceval.c:4645)
==537468==    by 0x2CA9F4: _PyEval_EvalFrameDefault (ceval.c:3191)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 416 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 417 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x305C3A: partial_fastcall.isra.2 (_functoolsmodule.c:169)
==537468==    by 0x305C3A: partial_call (_functoolsmodule.c:224)
==537468==    by 0x27E18A: _PyObject_FastCallKeywords (call.c:199)
==537468==    by 0x2CD625: call_function (ceval.c:4619)
==537468==    by 0x2CD625: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 418 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x22F30F: PyTuple_New (tupleobject.c:117)
==537468==    by 0x29925A: r_object (marshal.c:1225)
==537468==    by 0x2997AB: r_object (marshal.c:1405)
==537468==    by 0x2992F0: r_object (marshal.c:1231)
==537468==    by 0x299795: r_object (marshal.c:1402)
==537468==    by 0x299355: r_object (marshal.c:1231)
==537468==    by 0x299795: r_object (marshal.c:1402)
==537468==    by 0x29A470: read_object (marshal.c:1488)
==537468==    by 0x29A470: marshal_loads_impl.isra.5 (marshal.c:1800)
==537468==    by 0x29A470: marshal_loads (marshal.c.h:127)
==537468== 
==537468== 520 bytes in 1 blocks are possibly lost in loss record 419 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CA0A5: call_function (ceval.c:4616)
==537468==    by 0x2CA0A5: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468== 
==537468== 528 bytes in 1 blocks are possibly lost in loss record 424 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x17E48A: _PyObject_CallFunctionVa (call.c:961)
==537468== 
==537468== 528 bytes in 1 blocks are possibly lost in loss record 425 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2229D9: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537468==    by 0x27DB74: type_call (typeobject.c:951)
==537468== 
==537468== 528 bytes in 1 blocks are possibly lost in loss record 426 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x305C3A: partial_fastcall.isra.2 (_functoolsmodule.c:169)
==537468==    by 0x305C3A: partial_call (_functoolsmodule.c:224)
==537468==    by 0x231B9D: PyObject_Call (call.c:245)
==537468== 
==537468== 528 bytes in 1 blocks are possibly lost in loss record 427 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 528 bytes in 1 blocks are possibly lost in loss record 428 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2684FA: function_code_fastcall (call.c:283)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 430 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CA0A5: call_function (ceval.c:4616)
==537468==    by 0x2CA0A5: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 431 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x27DA01: property_descr_get (descrobject.c:1349)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 432 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537468==    by 0x27DDC8: type_call (typeobject.c:951)
==537468==    by 0x27DDC8: _PyObject_FastCallKeywords (call.c:199)
==537468==    by 0x2CE3D6: call_function (ceval.c:4619)
==537468==    by 0x2CE3D6: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 433 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 434 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468==    by 0x240AB1: _PyMethodDef_RawFastCallDict (call.c:530)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 435 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x27D129: slot_tp_call (typeobject.c:6402)
==537468==    by 0x27E18A: _PyObject_FastCallKeywords (call.c:199)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 436 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 437 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x27D069: slot_tp_init (typeobject.c:6636)
==537468== 
==537468== 536 bytes in 1 blocks are possibly lost in loss record 438 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 442 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 443 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x2236B9: function_code_fastcall (call.c:272)
==537468==    by 0x2236B9: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x27A403: _PyCodec_Lookup (codecs.c:155)
==537468==    by 0x3083D4: get_codec_name (pylifecycle.c:243)
==537468==    by 0x3083D4: get_locale_encoding (pylifecycle.c:278)
==537468==    by 0x3083D4: initfsencoding.isra.2 (pylifecycle.c:1632)
==537468==    by 0x32CF06: _Py_InitializeMainInterpreter (pylifecycle.c:947)
==537468==    by 0x32D72E: pymain_init_python_main (main.c:2809)
==537468==    by 0x32D72E: pymain_init (main.c:3016)
==537468==    by 0x32FC9B: pymain_main (main.c:3409)
==537468==    by 0x3300BB: _Py_UnixMain (main.c:3449)
==537468==    by 0x4CB00B2: (below main) (libc-start.c:308)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 444 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x2294C9: PyImport_ImportModuleLevelObject (import.c:1825)
==537468==    by 0x8E7ED84: __Pyx_Import.constprop.22 (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so)
==537468==    by 0x8E7CB78: __pyx_pymod_exec__common (in /home/guen/anaconda3/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 445 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x2CA9F4: do_call_core (ceval.c:4645)
==537468==    by 0x2CA9F4: _PyEval_EvalFrameDefault (ceval.c:3191)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 446 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 552 bytes in 1 blocks are possibly lost in loss record 447 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x231B9D: PyObject_Call (call.c:245)
==537468==    by 0x31DAF6: t_bootstrap (_threadmodule.c:994)
==537468==    by 0x2DAE17: pythread_wrapper (thread_pthread.h:174)
==537468== 
==537468== 560 bytes in 1 blocks are possibly lost in loss record 449 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468== 
==537468== 560 bytes in 1 blocks are possibly lost in loss record 450 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CA0A5: call_function (ceval.c:4616)
==537468==    by 0x2CA0A5: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x27D069: slot_tp_init (typeobject.c:6636)
==537468== 
==537468== 568 bytes in 1 blocks are possibly lost in loss record 452 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x17E53F: _PyObject_CallFunctionVa (call.c:935)
==537468==    by 0x2883B6: callmethod (call.c:1031)
==537468==    by 0x2883B6: PyObject_CallMethod (call.c:1050)
==537468== 
==537468== 568 bytes in 1 blocks are possibly lost in loss record 453 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 568 bytes in 1 blocks are possibly lost in loss record 454 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 568 bytes in 1 blocks are possibly lost in loss record 455 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268477: function_code_fastcall (call.c:272)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468==    by 0x240AB1: _PyMethodDef_RawFastCallDict (call.c:530)
==537468== 
==537468== 576 bytes in 1 blocks are possibly lost in loss record 582 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== 584 bytes in 1 blocks are possibly lost in loss record 584 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 592 bytes in 1 blocks are possibly lost in loss record 588 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 592 bytes in 1 blocks are possibly lost in loss record 589 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x27D129: slot_tp_call (typeobject.c:6402)
==537468==    by 0x27E18A: _PyObject_FastCallKeywords (call.c:199)
==537468==    by 0x2CD625: call_function (ceval.c:4619)
==537468==    by 0x2CD625: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 616 bytes in 1 blocks are possibly lost in loss record 590 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x2236B9: function_code_fastcall (call.c:272)
==537468==    by 0x2236B9: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x2CA9F4: do_call_core (ceval.c:4645)
==537468==    by 0x2CA9F4: _PyEval_EvalFrameDefault (ceval.c:3191)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C925F: call_function (ceval.c:4616)
==537468==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468== 
==537468== 632 bytes in 1 blocks are possibly lost in loss record 592 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537468==    by 0x27DDC8: type_call (typeobject.c:951)
==537468==    by 0x27DDC8: _PyObject_FastCallKeywords (call.c:199)
==537468==    by 0x2CE3D6: call_function (ceval.c:4619)
==537468==    by 0x2CE3D6: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468== 
==537468== 632 bytes in 1 blocks are possibly lost in loss record 593 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x324973: run_mod (pythonrun.c:1035)
==537468==    by 0x32ECF0: PyRun_FileExFlags (pythonrun.c:988)
==537468== 
==537468== 648 bytes in 1 blocks are possibly lost in loss record 597 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468== 
==537468== 656 bytes in 1 blocks are possibly lost in loss record 599 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CA0A5: call_function (ceval.c:4616)
==537468==    by 0x2CA0A5: _PyEval_EvalFrameDefault (ceval.c:3139)
==537468==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x27D129: slot_tp_call (typeobject.c:6402)
==537468== 
==537468== 688 bytes in 1 blocks are possibly lost in loss record 601 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== 688 bytes in 1 blocks are possibly lost in loss record 602 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 688 bytes in 1 blocks are possibly lost in loss record 603 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468==    by 0x240AB1: _PyMethodDef_RawFastCallDict (call.c:530)
==537468==    by 0x240BD0: _PyCFunction_FastCallDict (call.c:586)
==537468==    by 0x2CE838: do_call_core (ceval.c:4641)
==537468==    by 0x2CE838: _PyEval_EvalFrameDefault (ceval.c:3191)
==537468== 
==537468== 696 bytes in 1 blocks are possibly lost in loss record 604 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537468==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537468==    by 0x27DB74: type_call (typeobject.c:951)
==537468==    by 0x223C0E: _PyObject_FastCallDict (call.c:125)
==537468==    by 0x287AF9: builtin___build_class__ (bltinmodule.c:253)
==537468== 
==537468== 704 bytes in 1 blocks are possibly lost in loss record 605 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x22F30F: PyTuple_New (tupleobject.c:117)
==537468==    by 0x29925A: r_object (marshal.c:1225)
==537468==    by 0x2997C1: r_object (marshal.c:1408)
==537468==    by 0x299355: r_object (marshal.c:1231)
==537468==    by 0x299795: r_object (marshal.c:1402)
==537468==    by 0x29A470: read_object (marshal.c:1488)
==537468==    by 0x29A470: marshal_loads_impl.isra.5 (marshal.c:1800)
==537468==    by 0x29A470: marshal_loads (marshal.c.h:127)
==537468==    by 0x268F3C: _PyMethodDef_RawFastCallKeywords (call.c:648)
==537468==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537468== 
==537468== 1,056 bytes in 2 blocks are possibly lost in loss record 758 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x22954B: import_find_and_load (import.c:1648)
==537468==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537468==    by 0x2CB6D8: import_name (ceval.c:4770)
==537468==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== 1,066 bytes in 1 blocks are possibly lost in loss record 759 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x253F8C: PyUnicode_New (unicodeobject.c:1322)
==537468==    by 0x25591D: _PyUnicode_FromUCS1 (unicodeobject.c:2216)
==537468==    by 0x25591D: PyUnicode_FromKindAndData (unicodeobject.c:2287)
==537468==    by 0x29945D: r_object (marshal.c:1169)
==537468==    by 0x299355: r_object (marshal.c:1231)
==537468==    by 0x299795: r_object (marshal.c:1402)
==537468==    by 0x29A470: read_object (marshal.c:1488)
==537468==    by 0x29A470: marshal_loads_impl.isra.5 (marshal.c:1800)
==537468==    by 0x29A470: marshal_loads (marshal.c.h:127)
==537468==    by 0x268F3C: _PyMethodDef_RawFastCallKeywords (call.c:648)
==537468==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537468==    by 0x2CDA5C: call_function (ceval.c:4568)
==537468==    by 0x2CDA5C: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== 1,120 bytes in 2 blocks are possibly lost in loss record 827 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468== 
==537468== 1,240 bytes in 2 blocks are possibly lost in loss record 832 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 1,248 bytes in 2 blocks are possibly lost in loss record 833 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468== 
==537468== 1,248 bytes in 2 blocks are possibly lost in loss record 834 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468== 
==537468== 1,376 bytes in 2 blocks are possibly lost in loss record 843 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2CD6C8: call_function (ceval.c:4616)
==537468==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537468== 
==537468== 1,584 bytes in 3 blocks are possibly lost in loss record 853 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x22954B: import_find_and_load (import.c:1648)
==537468==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537468==    by 0x2A76E9: builtin___import__ (bltinmodule.c:312)
==537468==    by 0x240C54: cfunction_call_varargs (call.c:757)
==537468==    by 0x240C54: PyCFunction_Call (call.c:788)
==537468== 
==537468== 1,656 bytes in 3 blocks are possibly lost in loss record 854 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468==    by 0x22361B: PyEval_EvalCode (ceval.c:524)
==537468==    by 0x2D87B0: builtin_exec_impl.isra.12 (bltinmodule.c:1079)
==537468==    by 0x2D87B0: builtin_exec (bltinmodule.c.h:283)
==537468==    by 0x240AB1: _PyMethodDef_RawFastCallDict (call.c:530)
==537468== 
==537468== 1,712 bytes in 2 blocks are possibly lost in loss record 856 of 1,036
==537468==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468== 
==537468== 1,824 bytes in 3 blocks are possibly lost in loss record 859 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x22F30F: PyTuple_New (tupleobject.c:117)
==537468==    by 0x29925A: r_object (marshal.c:1225)
==537468==    by 0x2997AB: r_object (marshal.c:1405)
==537468==    by 0x299355: r_object (marshal.c:1231)
==537468==    by 0x299795: r_object (marshal.c:1402)
==537468==    by 0x29A470: read_object (marshal.c:1488)
==537468==    by 0x29A470: marshal_loads_impl.isra.5 (marshal.c:1800)
==537468==    by 0x29A470: marshal_loads (marshal.c.h:127)
==537468==    by 0x268F3C: _PyMethodDef_RawFastCallKeywords (call.c:648)
==537468==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537468== 
==537468== 2,568 bytes in 3 blocks are possibly lost in loss record 924 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x26868A: function_code_fastcall (call.c:283)
==537468==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468== 
==537468== 2,760 bytes in 5 blocks are possibly lost in loss record 929 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537468==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537468==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537468==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537468==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x2294C9: PyImport_ImportModuleLevelObject (import.c:1825)
==537468==    by 0x2CB6D8: import_name (ceval.c:4770)
==537468==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537468== 
==537468== 3,312 bytes in 6 blocks are possibly lost in loss record 937 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537468==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x2294C9: PyImport_ImportModuleLevelObject (import.c:1825)
==537468==    by 0x2CB6D8: import_name (ceval.c:4770)
==537468==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== 3,696 bytes in 7 blocks are possibly lost in loss record 944 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x22954B: import_find_and_load (import.c:1648)
==537468==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537468==    by 0x2A76E9: builtin___import__ (bltinmodule.c:312)
==537468== 
==537468== 7,920 bytes in 15 blocks are possibly lost in loss record 991 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537468==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537468==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537468==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537468==    by 0x268601: function_code_fastcall (call.c:272)
==537468==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x22373A: function_code_fastcall (call.c:283)
==537468==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537468==    by 0x23EC3D: object_vacall (call.c:1202)
==537468==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537468==    by 0x22954B: import_find_and_load (import.c:1648)
==537468==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537468==    by 0x2CB6D8: import_name (ceval.c:4770)
==537468==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537468== 
==537468== 135,449 bytes in 69 blocks are possibly lost in loss record 1,032 of 1,036
==537468==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537468==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537468==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537468==    by 0x253F8C: PyUnicode_New (unicodeobject.c:1322)
==537468==    by 0x256403: _PyUnicode_FromASCII (unicodeobject.c:2180)
==537468==    by 0x2F13AB: unicode_strip_impl (unicodeobject.c:12486)
==537468==    by 0x2F13AB: unicode_strip (unicodeobject.c.h:508)
==537468==    by 0x268F98: _PyMethodDef_RawFastCallKeywords (call.c:655)
==537468==    by 0x27DC6E: _PyMethodDescr_FastCallKeywords (descrobject.c:288)
==537468==    by 0x2CD81B: call_function (ceval.c:4593)
==537468==    by 0x2CD81B: _PyEval_EvalFrameDefault (ceval.c:3110)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537468==    by 0x2C8FD5: call_function (ceval.c:4616)
==537468==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537468==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537468== 
==537468== LEAK SUMMARY:
==537468==    definitely lost: 263 bytes in 6 blocks
==537468==    indirectly lost: 161 bytes in 4 blocks
==537468==      possibly lost: 197,435 bytes in 176 blocks
==537468==    still reachable: 4,770,124 bytes in 3,683 blocks
==537468==         suppressed: 64 bytes in 2 blocks
==537468== Reachable blocks (those to which a pointer was found) are not shown.
==537468== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==537468== 
==537468== Use --track-origins=yes to see where uninitialised values come from
==537468== For lists of detected and suppressed errors, rerun with: -s
==537468== ERROR SUMMARY: 77 errors from 73 contexts (suppressed: 3627 from 231)
==537401== 
==537401== HEAP SUMMARY:
==537401==     in use at exit: 1,799,136 bytes in 1,173 blocks
==537401==   total heap usage: 9,841 allocs, 8,668 frees, 32,609,858 bytes allocated
==537401== 
==537401== 47 bytes in 1 blocks are definitely lost in loss record 134 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x4018CED: _dl_exception_create (dl-exception.c:78)
==537401==    by 0x4DEC807: _dl_signal_error (dl-error-skeleton.c:117)
==537401==    by 0x400AD89: _dl_map_object (dl-load.c:2231)
==537401==    by 0x4015D36: dl_open_worker (dl-open.c:513)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x40155F9: _dl_open (dl-open.c:837)
==537401==    by 0x4E7C34B: dlopen_doit (dlopen.c:66)
==537401==    by 0x4DEC8B7: _dl_catch_exception (dl-error-skeleton.c:208)
==537401==    by 0x4DEC982: _dl_catch_error (dl-error-skeleton.c:227)
==537401==    by 0x4E7CB58: _dlerror_run (dlerror.c:170)
==537401==    by 0x4E7C3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==537401== 
==537401== 528 bytes in 1 blocks are possibly lost in loss record 173 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537401==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537401==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537401==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537401==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x23EC3D: object_vacall (call.c:1202)
==537401==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537401==    by 0x22954B: import_find_and_load (import.c:1648)
==537401==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537401==    by 0x2CB6D8: import_name (ceval.c:4770)
==537401==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401== 
==537401== 528 bytes in 1 blocks are possibly lost in loss record 174 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x22302F: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537401== 
==537401== 536 bytes in 1 blocks are possibly lost in loss record 175 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2CA0A5: call_function (ceval.c:4616)
==537401==    by 0x2CA0A5: _PyEval_EvalFrameDefault (ceval.c:3139)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401== 
==537401== 536 bytes in 1 blocks are possibly lost in loss record 176 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x268916: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2CD6C8: call_function (ceval.c:4616)
==537401==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x27DA01: property_descr_get (descrobject.c:1349)
==537401== 
==537401== 536 bytes in 1 blocks are possibly lost in loss record 177 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537401==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537401==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537401==    by 0x27DDC8: type_call (typeobject.c:951)
==537401==    by 0x27DDC8: _PyObject_FastCallKeywords (call.c:199)
==537401==    by 0x2CE3D6: call_function (ceval.c:4619)
==537401==    by 0x2CE3D6: _PyEval_EvalFrameDefault (ceval.c:3139)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401== 
==537401== 552 bytes in 1 blocks are possibly lost in loss record 179 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401== 
==537401== 552 bytes in 1 blocks are possibly lost in loss record 180 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537401==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537401==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537401==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537401==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537401==    by 0x2236B9: function_code_fastcall (call.c:272)
==537401==    by 0x2236B9: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x27A403: _PyCodec_Lookup (codecs.c:155)
==537401==    by 0x3083D4: get_codec_name (pylifecycle.c:243)
==537401==    by 0x3083D4: get_locale_encoding (pylifecycle.c:278)
==537401==    by 0x3083D4: initfsencoding.isra.2 (pylifecycle.c:1632)
==537401==    by 0x32CF06: _Py_InitializeMainInterpreter (pylifecycle.c:947)
==537401==    by 0x32D72E: pymain_init_python_main (main.c:2809)
==537401==    by 0x32D72E: pymain_init (main.c:3016)
==537401==    by 0x32FC9B: pymain_main (main.c:3409)
==537401==    by 0x3300BB: _Py_UnixMain (main.c:3449)
==537401==    by 0x4CB00B2: (below main) (libc-start.c:308)
==537401== 
==537401== 552 bytes in 1 blocks are possibly lost in loss record 181 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x214EFC: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x214EFC: pymalloc_realloc (obmalloc.c:1905)
==537401==    by 0x214EFC: _PyObject_Realloc (obmalloc.c:1924)
==537401==    by 0x214EFC: PyObject_Realloc (obmalloc.c:651)
==537401==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537401==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x223804: _PyFunction_FastCallDict (call.c:376)
==537401==    by 0x23EC3D: object_vacall (call.c:1202)
==537401==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537401==    by 0x2294C9: PyImport_ImportModuleLevelObject (import.c:1825)
==537401==    by 0x2CB6D8: import_name (ceval.c:4770)
==537401==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2235F3: PyEval_EvalCodeEx (ceval.c:3959)
==537401== 
==537401== 568 bytes in 1 blocks are possibly lost in loss record 183 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2CD6C8: call_function (ceval.c:4616)
==537401==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x17E53F: _PyObject_CallFunctionVa (call.c:935)
==537401==    by 0x2883B6: callmethod (call.c:1031)
==537401==    by 0x2883B6: PyObject_CallMethod (call.c:1050)
==537401== 
==537401== 576 bytes in 1 blocks are possibly lost in loss record 284 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2CD6C8: call_function (ceval.c:4616)
==537401==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401== 
==537401== 592 bytes in 1 blocks are possibly lost in loss record 288 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C925F: call_function (ceval.c:4616)
==537401==    by 0x2C925F: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401== 
==537401== 632 bytes in 1 blocks are possibly lost in loss record 290 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x22244B: _PyEval_EvalCodeWithName (ceval.c:3691)
==537401==    by 0x223A2F: _PyFunction_FastCallDict (call.c:376)
==537401==    by 0x23E942: _PyObject_Call_Prepend (call.c:908)
==537401==    by 0x28038D: slot_tp_new (typeobject.c:6665)
==537401==    by 0x27DDC8: type_call (typeobject.c:951)
==537401==    by 0x27DDC8: _PyObject_FastCallKeywords (call.c:199)
==537401==    by 0x2CE3D6: call_function (ceval.c:4619)
==537401==    by 0x2CE3D6: _PyEval_EvalFrameDefault (ceval.c:3139)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401== 
==537401== 688 bytes in 1 blocks are possibly lost in loss record 295 of 581
==537401==    at 0x4A3DDAD: realloc (vg_replace_malloc.c:1192)
==537401==    by 0x25ACAC: _PyObject_GC_Resize (gcmodule.c:1758)
==537401==    by 0x2683F2: _PyFrame_New_NoTrack (frameobject.c:726)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x26868A: function_code_fastcall (call.c:283)
==537401==    by 0x26868A: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2CD6C8: call_function (ceval.c:4616)
==537401==    by 0x2CD6C8: _PyEval_EvalFrameDefault (ceval.c:3093)
==537401== 
==537401== 1,066 bytes in 1 blocks are possibly lost in loss record 434 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x253F8C: PyUnicode_New (unicodeobject.c:1322)
==537401==    by 0x25591D: _PyUnicode_FromUCS1 (unicodeobject.c:2216)
==537401==    by 0x25591D: PyUnicode_FromKindAndData (unicodeobject.c:2287)
==537401==    by 0x29945D: r_object (marshal.c:1169)
==537401==    by 0x299355: r_object (marshal.c:1231)
==537401==    by 0x299795: r_object (marshal.c:1402)
==537401==    by 0x29A470: read_object (marshal.c:1488)
==537401==    by 0x29A470: marshal_loads_impl.isra.5 (marshal.c:1800)
==537401==    by 0x29A470: marshal_loads (marshal.c.h:127)
==537401==    by 0x268F3C: _PyMethodDef_RawFastCallKeywords (call.c:648)
==537401==    by 0x269230: _PyCFunction_FastCallKeywords (call.c:734)
==537401==    by 0x2CDA5C: call_function (ceval.c:4568)
==537401==    by 0x2CDA5C: _PyEval_EvalFrameDefault (ceval.c:3093)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401== 
==537401== 1,584 bytes in 3 blocks are possibly lost in loss record 495 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x23EC3D: object_vacall (call.c:1202)
==537401==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537401==    by 0x22954B: import_find_and_load (import.c:1648)
==537401==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537401==    by 0x2A76E9: builtin___import__ (bltinmodule.c:312)
==537401== 
==537401== 1,584 bytes in 3 blocks are possibly lost in loss record 496 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x22E98D: _PyObject_GC_Alloc (gcmodule.c:1693)
==537401==    by 0x22E98D: _PyObject_GC_Malloc (gcmodule.c:1715)
==537401==    by 0x22F0CE: _PyObject_GC_NewVar (gcmodule.c:1744)
==537401==    by 0x2683B1: _PyFrame_New_NoTrack (frameobject.c:713)
==537401==    by 0x268601: function_code_fastcall (call.c:272)
==537401==    by 0x268601: _PyFunction_FastCallKeywords (call.c:408)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x22373A: function_code_fastcall (call.c:283)
==537401==    by 0x22373A: _PyFunction_FastCallDict (call.c:322)
==537401==    by 0x23EC3D: object_vacall (call.c:1202)
==537401==    by 0x28328C: _PyObject_CallMethodIdObjArgs (call.c:1252)
==537401==    by 0x22954B: import_find_and_load (import.c:1648)
==537401==    by 0x22954B: PyImport_ImportModuleLevelObject (import.c:1760)
==537401==    by 0x2CB6D8: import_name (ceval.c:4770)
==537401==    by 0x2CB6D8: _PyEval_EvalFrameDefault (ceval.c:2600)
==537401== 
==537401== 135,449 bytes in 69 blocks are possibly lost in loss record 580 of 581
==537401==    at 0x4A38FB5: malloc (vg_replace_malloc.c:380)
==537401==    by 0x2150AE: _PyObject_Malloc (obmalloc.c:1584)
==537401==    by 0x2150AE: PyObject_Malloc (obmalloc.c:633)
==537401==    by 0x253F8C: PyUnicode_New (unicodeobject.c:1322)
==537401==    by 0x256403: _PyUnicode_FromASCII (unicodeobject.c:2180)
==537401==    by 0x2F13AB: unicode_strip_impl (unicodeobject.c:12486)
==537401==    by 0x2F13AB: unicode_strip (unicodeobject.c.h:508)
==537401==    by 0x268F98: _PyMethodDef_RawFastCallKeywords (call.c:655)
==537401==    by 0x27DC6E: _PyMethodDescr_FastCallKeywords (descrobject.c:288)
==537401==    by 0x2CD81B: call_function (ceval.c:4593)
==537401==    by 0x2CD81B: _PyEval_EvalFrameDefault (ceval.c:3110)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401==    by 0x2688B4: _PyFunction_FastCallKeywords (call.c:433)
==537401==    by 0x2C8FD5: call_function (ceval.c:4616)
==537401==    by 0x2C8FD5: _PyEval_EvalFrameDefault (ceval.c:3124)
==537401==    by 0x2226F8: _PyEval_EvalCodeWithName (ceval.c:3930)
==537401== 
==537401== LEAK SUMMARY:
==537401==    definitely lost: 47 bytes in 1 blocks
==537401==    indirectly lost: 0 bytes in 0 blocks
==537401==      possibly lost: 147,059 bytes in 89 blocks
==537401==    still reachable: 1,651,998 bytes in 1,082 blocks
==537401==         suppressed: 32 bytes in 1 blocks
==537401== Reachable blocks (those to which a pointer was found) are not shown.
==537401== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==537401== 
==537401== Use --track-origins=yes to see where uninitialised values come from
==537401== For lists of detected and suppressed errors, rerun with: -s
==537401== ERROR SUMMARY: 25 errors from 21 contexts (suppressed: 5274 from 355)
